---
# tasks file for roles/omero-user

- ansible.builtin.include_tasks: reset-root-password.yml
  when: "omero_user_reset_root_password | length > 0"

- ansible.builtin.include_tasks: groups.yml
  when: "omero_group_create | length > 0"

- include_tasks: users.yml
  when: "omero_user_create | length > 0"

- include_tasks: reset-password.yml
  when: "omero_user_create | length > 0"
